<a href="https://colab.research.google.com/github/lvsciagin/job_fraud_detection/blob/feature/fraud2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Useful Links
https://medium.com/@syahrizacio/predicting-fraud-job-vacancies-with-99-accuracy-using-natural-language-processing-in-python-1f17704b82e4

In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv(r'Job_Frauds.csv', encoding="ISO-8859-1")

In [3]:
df.head()

Job Title        Job Location Department  \
0                           Marketing Intern    US, NY, New York  Marketing   
1  Customer Service - Cloud Video Production      NZ, , Auckland    Success   
2    Commissioning Machinery Assistant (CMA)       US, IA, Wever        NaN   
3          Account Executive - Washington DC  US, DC, Washington      Sales   
4                        Bill Review Manager  US, FL, Fort Worth        NaN   

  Range_of_Salary                                            Profile  \
0             NaN  We're Food52, and we've created a groundbreaki...   
1             NaN  90 Seconds, the worlds Cloud Video Production ...   
2             NaN  Valor Services provides Workforce Solutions th...   
3             NaN  Our passion for improving quality of life thro...   
4             NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                     Job_Description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Re...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        Requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS,...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                        Job_Benefits  Telecomunication  \
0                                                NaN                 0   
1  What you will get from usThrough being part of...                 0   
2                                                NaN                 0   
3  Our culture is anything but corporate—we hav...                 0   
4                              Full Benefits Offered                 0   

   Comnpany_Logo Type_of_Employment        Experience      Qualification  \
0              1              Other        Internship                NaN   
1              1          Full-time    Not Applicable                NaN   
2              1                NaN               NaN                NaN   
3              1          Full-time  Mid-Senior level  Bachelor's Degree   
4              1          Full-time  Mid-Senior level  Bachelor's Degree   

            Type_of_Industry            Operations  Fraudulent  
0                        NaN             Marketing           0  
1  Marketing and Advertising      Customer Service           0  
2                        NaN                   NaN           0  
3          Computer Software                 Sales           0  
4     Hospital & Health Care  Health Care Provider           0

In [5]:
# Using panda profile to get an overview of the data
# Installing panda profiling requirements for exploratory data analysis
! pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="Job Listings", html={'style': {'full_width': True}}, sort=None)
profile.to_notebook_iframe()

     | 25.9 MB 5.3 MB/s
     |████████████████████████████████| 10.9 MB 4.5 MB/s 
     |████████████████████████████████| 596 kB 63.1 MB/s 
     |████████████████████████████████| 102 kB 10.4 MB/s 
     |████████████████████████████████| 690 kB 61.2 MB/s 
     |████████████████████████████████| 4.7 MB 45.8 MB/s 
     |████████████████████████████████| 63 kB 1.3 MB/s 
     |████████████████████████████████| 812 kB 52.1 MB/s 
     |████████████████████████████████| 38.1 MB 1.5 MB/s 
  Created wheel for pandas-profiling: filename=pandas_profiling-3.1.1-py2.py3-none-any.whl size=261287 sha256=67534b02e1c2aeefa65acfc81169d4a3301ba5050649b5c2845c4edbc1ae33ae
  Stored in directory: /tmp/pip-ephem-wheel-cache-w8hh53ky/wheels/cc/d5/09/083fb07c9363a2f45854b0e3a7de7d7c560f07da74b9e9769d
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=84625d118ff7f89043aa3da4306313fe4445df4b02753ce6001e9d9221fc113e
  Stored in directory: /root/.cache/pip/wheels/70/e1/52/5b14

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
df=df[['Job_Description','Requirements','Fraudulent']]
df.head()

Job_Description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Re...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        Requirements  Fraudulent  
0  Experience with content management systems a m...           0  
1  What we expect from you:Your key responsibilit...           0  
2  Implement pre-commissioning and commissioning ...           0  
3  EDUCATION: Bachelor’s or Master’s in GIS,...           0  
4  QUALIFICATIONS:RN license in the State of Texa...           0

In [10]:
###Drop Nan Values
df=df.dropna()

In [11]:
df.shape

(15185, 3)

In [13]:
## Get the Independent Features

x=df.drop('Fraudulent',axis=1)

In [14]:
## Get the Dependent features
y=df['Fraudulent']

In [15]:
y.value_counts()

0    14473
1      712
Name: Fraudulent, dtype: int64

In [4]:
import tensorflow as tf
tf .__version__

'2.8.0'

In [6]:
# importing tensorflow dependancies
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [7]:
voc_size = 5000

In [16]:
# One-Hot Presentation
message = x.copy()

In [17]:
message['Job_Description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!Â\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious aboutÂ\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. Â\xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.Â\xa090 Seconds, the worlds Cloud Video Production Service -Â\xa0http

In [18]:
message.reset_index(inplace=True)

In [19]:
#eliminating stopwords 

import nltk
import re
from nltk.corpus import stopwords

In [23]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [25]:
# using PortStemmer

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['Job_Description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus

['food fast grow jame beard award win onlin food commun crowd sourc curat recip hub current interview full part time unpaid intern work small team editor execut develop new york citi headquart reproduc repackag exist food content number partner site huffington post yahoo buzzfe variou content manag systemsresearch blog websit provis food affili programassist day day affili program support screen affili assist affili inquiriessupport pr amp event neededhelp offic administr work file mail prepar meetingswork develop document bug suggest improv sitesupport market execut staff',
 'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn globa

In [27]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[4942,
 1540,
 1101,
 972,
 1739,
 3393,
 1104,
 4100,
 2871,
 1199,
 71,
 4538,
 4434,
 448,
 3813,
 1969,
 3020,
 2200,
 2144,
 3303,
 533,
 4663,
 4967,
 2147,
 1104,
 2518,
 267,
 1455,
 3655,
 1659,
 4659,
 1461,
 3390,
 3729,
 1028,
 2147,
 2380,
 3393,
 1104,
 2943,
 4792,
 1978,
 333,
 1053,
 1963,
 4434,
 4434,
 411,
 2416,
 4967,
 1963,
 4434,
 3668,
 1613,
 2147,
 2147,
 1001,
 2097,
 4236,
 4474,
 2802,
 3747,
 1601,
 2645,
 3707,
 1296,
 1096,
 1932,
 687,
 2471,
 963,
 1995,
 1978,
 1572,
 1597,
 3209,
 4642,
 1545,
 3504,
 3193,
 2745,
 583,
 687,
 1978,
 2745,
 1188,
 3764,
 3729,
 4663,
 4967,
 2147,
 1104,
 1246,
 4101,
 4541,
 1601,
 1648,
 462,
 4875,
 4583,
 1740,
 2122,
 2122,
 4875,
 380,
 4763,
 3764,
 3729,
 4663,
 4967,
 2147,
 1104,
 460,
 4474,
 657,
 2345,
 3899,
 2734,
 215,
 4967,
 756,
 2361,
 4043,
 4777,
 3729,
 302,
 4932,
 4434,
 65,
 4663,
 2780,
 1190,
 3764,
 2967,
 2801,
 3697,
 4078,
 4507,
 1714,
 2097,
 2508,
 4967,
 2147,
 760,
 4434,
 1465,


In [28]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4242  756 4434 ... 2015 1375 1499]
 [ 411 2088  693 ... 1006 3619 3857]
 [   0    0    0 ... 3326  354  687]
 ...
 [1378 2466  799 ... 2854 1569  588]
 [3329 1954 4618 ... 3730 3209 1963]
 [1051 3384  789 ... 2212 4894 2518]]


In [29]:
embedded_docs[0]

array([4242,  756, 4434, 1932, 2732,  201, 4418,  325, 1096, 1819,  770,
        770, 1096, 4064,  471,  792, 1096, 3875, 1096, 4832, 2692, 4850,
        598, 3677, 1979, 3813, 2097, 1750, 4951, 3617, 3598, 1446, 3139,
        422,  494,  195, 4649, 2015, 1375, 1499], dtype=int32)

In [30]:

## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              120800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None


In [31]:
len(embedded_docs),y.shape

(15185, (15185,))

In [32]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [33]:
X_final[1]

array([ 411, 2088,  693, 3232, 2287, 2893,   66, 3764, 4043, 1490, 4967,
       3549, 1601, 4474, 3091, 3729,  350, 3091, 3527, 3887, 3792, 2141,
        360, 1979, 2270, 1375, 2734, 3962, 4850, 4729, 2270, 1979,  255,
       2745, 2668, 2385,  818, 1006, 3619, 3857], dtype=int32)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [36]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=64)

Epoch 1/12
178/178 [==============================] - 24s 92ms/step - loss: 0.1807 - accuracy: 0.9586 - val_loss: 0.1424 - val_accuracy: 0.9589
Epoch 2/12
178/178 [==============================] - 15s 85ms/step - loss: 0.0784 - accuracy: 0.9773 - val_loss: 0.1895 - val_accuracy: 0.9631
Epoch 3/12
178/178 [==============================] - 15s 86ms/step - loss: 0.0525 - accuracy: 0.9863 - val_loss: 0.1313 - val_accuracy: 0.9668
Epoch 4/12
178/178 [==============================] - 16s 88ms/step - loss: 0.0356 - accuracy: 0.9907 - val_loss: 0.1510 - val_accuracy: 0.9671
Epoch 5/12
178/178 [==============================] - 15s 87ms/step - loss: 0.0247 - accuracy: 0.9928 - val_loss: 0.1669 - val_accuracy: 0.9668
Epoch 6/12
178/178 [==============================] - 15s 87ms/step - loss: 0.0181 - accuracy: 0.9956 - val_loss: 0.1765 - val_accuracy: 0.9660
Epoch 7/12
178/178 [==============================] - 16s 91ms/step - loss: 0.0132 - accuracy: 0.9967 - val_loss: 0.2467 - val_accuracy:

In [58]:
# Model Performance & Accuracy 
y_pred = np.argmax(model1.predict(X_test), axis=-1)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[3585,    0],
       [ 212,    0]])

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9441664471951541

In [60]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      3585
           1       0.00      0.00      0.00       212

    accuracy                           0.94      3797
   macro avg       0.47      0.50      0.49      3797
weighted avg       0.89      0.94      0.92      3797



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
